[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
source ~/dotfiles/.config/nvim/plugins/NERDTree.rc.vim
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ~/dotfiles/.config/nvim/plugins/lightline.rc.vim
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
build = 'bash ./install.sh'
hook_add = '''
source ~/dotfiles/.config/nvim/plugins/LanguageClient-neovim.rc.vim
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft= 'rust'
hook_add = '''
source ~/dotfiles/.config/nvim/plugins/rust.rc.vim
'''
